### ISSUE TITLE
Can I get the label information in the KSC results

### ISSUE THREAD

**Issue by rc2000123** [Aganonce/pyksc#1]
how do I know which items are in which cluster?

**Comment by Aganonce** [comment]
According to the function comments of the main file, KSC returns two tuples: results and centroids. Both are dictionaries. Results contain clustered time series members where the key is the cluster number and the value is a list containing lists of float values representing y-values of time series where the index is the x-value. Centroids contain the centroid time series where key is the cluster number and the value is a list containing the time series shape of the centroid.
